language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build  -t beardedslav/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true beardedslav/docker-react npm run test